### ISSUE TITLE
Separate components into individual repos

### ISSUE THREAD

**Issue by leonard-thieu** [leonard-thieu/toofz-necrodancer#18]
While a monolithic solution structure was convenient, it starts getting in the way when integrating a CI/CD solution. This repository's components will be separated into individual components. This serves as a tracking ticket. Note that leaderboard services will have to undergo some refactoring before being separated.

- [x] SqlBulkUpsert (#13)
- [x] toofz (#14)
- [x] toofz.NecroDancer (#15)
- [x] toofz.NecroDancer.EntityFramework (#16)
- [x] toofz.NecroDancer.Web.ImageManager (#17)
- [x] toofz.NecroDancer.Web.LoadData (#19)
- [x] toofz.NecroDancer.WebClient (#20)
- [x] toofz.NecroDancer.Leaderboards (#33)
- [x] Leaderboard Services
  - [x] toofz.NecroDancer.Leaderboards.Services.Common (#34)
  - [x] Leaderboards
    - [x] Refactoring (#26)
    - [x] Separation (#36)
  - [x] Players
    - [x] Refactoring (#21)
    - [x] Separation (#37)
  - [x] Replays
    - [x] Refactoring (#21)
    - [x] Separation (#38)
  - [x] Services
    - [x] Refactoring (#26)
- [x] toofz.NecroDancer.Web.Api
  - [x] Refactoring (#29)
  - [x] Separation (#35)
